# Site settings
title: "Mendhak / Code"
email: 
description: "Tech and development notes"
baseurl: "/jekyll-testing"
url: "https://code.mendhak.com/"
title_description: ""
title_image: "https://avatars2.githubusercontent.com/u/746276?s=460&v=4"
github_repository: https://github.com/mendhak/carte-noire
post_limit: 10


# Footer
footer_left:  
footer_right: 

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title
exclude: [vendor]
