# Site settings
title: "Carte Noire"
email: 
description: "Testing Carte Noire."
baseurl: "/jekyll-testing"
url: "https://code.mendhak.com/"
title_description: "Carte Noire theme, but with social bits disabled."
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: 
disqus_account: 
github_repository: https://github.com/mendhak/carte-noire
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username:
github_username: 
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title
exclude: [vendor]
