# Site settings
title: "Mendhak / Code"
email: 
description: "Tech and development notes"
baseurl: "/jekyll-testing"
url: "https://code.mendhak.com/"
title_description: ""
title_image: "https://avatars2.githubusercontent.com/u/746276?s=460&v=4"
google_analytics: 
github_repository: https://github.com/mendhak/carte-noire
post_limit: 5


# Footer
footer_left:  "<i class=\"fa fa-camera\"></i> <a href=\"https://mendhak.com\">mendhak</a>"
footer_right: "<i class=\"fa fa-code\"></i> <a href=\"https://github.com/mendhak\">Github</a> &nbsp;<i class=\"fab fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title
exclude: [vendor]
